import { Metadata } from "next"


export const metadata: Metadata = {
    title: 'Products',
    description: 'Generated by Next.js',
  }


export default function ProductsLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
          {children}
        </>
    )
  }